In [5]:
import torch
a_t = torch.empty(2,3)
print(a_t)
a_t = torch.rand(2,3)
print(a_t)
a_t = torch.full([2,3],7)
print(a_t)
a_t = torch.eye(3,3)
print(a_t)

tensor([[0.0000e+00, 8.9082e-39, 1.8754e+28],
        [4.0611e-08, 4.2420e-08, 1.2869e-11]])
tensor([[0.5371, 0.8896, 0.7393],
        [0.9494, 0.7148, 0.0201]])
tensor([[7, 7, 7],
        [7, 7, 7]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [6]:
import torch
a_t = torch.tensor([1.2,2.1])
print(a_t.dtype)
a_t = torch.FloatTensor([1.2,2.1])
print(a_t.dtype) #尝试 torch.IntTensor 声明 int 型 tensor
a_t = a_t.double() #尝试 a_t.float() 及 a_t.int() 实现数据类型转换
torch.set_default_tensor_type(torch.DoubleTensor)
a_t = torch.tensor([1.2,2.1])
print(a_t.dtype)
b_t = torch.FloatTensor([1.2,2.1])
print(b_t.dtype)

torch.float32
torch.float32
torch.float64
torch.float32


In [7]:
a = torch.ones(2, 3); b = torch.ones(3)
print(a+b) #广播
print(torch.add(a, b))
print(a.add(b)); print(a)
print(a.add_(b)); print(a) #函数名以 结尾的是 inplace 方式，会修改调用者自己的数据

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [8]:
a = torch.ones(2, 3);
print(a.shape)
print(torch.sum(a).shape)
print(a.sum(axis=0).shape) #压缩指定维度
print(a.sum(axis=1).shape)
print(a.sum(axis=1, keepdim=True).shape) #保留维度

torch.Size([2, 3])
torch.Size([])
torch.Size([3])
torch.Size([2])
torch.Size([2, 1])


In [24]:
import torch
a=torch.ones(2,3,4)
print(a.size())
b=torch.flatten(a, start_dim=1)
print(b.size())

torch.Size([2, 3, 4])
torch.Size([2, 12])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [1]:
import torch
a = torch.ones(2, 3);
print(a.shape)
print(torch.sum(a).shape)
print(a.sum(axis=0).shape) #压缩指定维度
print(a.sum(axis=1).shape)
print(a.sum(axis=1, keepdim=True).shape) #保留维度

torch.Size([2, 3])
torch.Size([])
torch.Size([3])
torch.Size([2])
torch.Size([2, 1])


In [11]:
# view/reshape
#保证 tensor 数据大小不变，对 tensor 数据进行形状的重新定义与转换
import torch
a_t= torch.tensor ([1, 2, 3, 4, 5, 6]); b_t = a_t.view (3,2)
print(b_t)
# squeeze/unsqueeze 删减维度或者增加维度操作
a_t= torch.rand (3, 1, 2); print(a_t.shape)
b_t= a_t.squeeze(); print(b_t.shape); c_t = a_t.unsqueeze (3);print( c_t.shape)
# transpose/permute：类似矩阵转置操作，对多维的数据具有多次或者单次的转换操作

a_t= torch.rand (3, 1, 2); print(a_t.shape); b_t = a_t.transpose (0,1); print(b_t.shape)
c_t= a_t.permute (1,0,2);
print(c_t.shape)
# expand：扩展某个 size 为 1 的维度。如 ( 扩展为 (

x=torch.randn(2,2,1); print(x); y=x.expand(2,2,3); print(y); x[0,1] = 0; print(y) #共享内存

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 1, 2])
torch.Size([3, 2])
torch.Size([3, 1, 2, 1])
torch.Size([3, 1, 2])
torch.Size([1, 3, 2])
torch.Size([1, 3, 2])
tensor([[[-0.5911],
         [ 0.4556]],

        [[-0.3899],
         [-0.6758]]])
tensor([[[-0.5911, -0.5911, -0.5911],
         [ 0.4556,  0.4556,  0.4556]],

        [[-0.3899, -0.3899, -0.3899],
         [-0.6758, -0.6758, -0.6758]]])
tensor([[[-0.5911, -0.5911, -0.5911],
         [ 0.0000,  0.0000,  0.0000]],

        [[-0.3899, -0.3899, -0.3899],
         [-0.6758, -0.6758, -0.6758]]])


In [12]:
#当遇到 Tensor 不支持的操作时，可先转成 Numpy 数组，处理后再转回 tensor ，开销很小。
import torch
a =torch.rand (4, 3, 28,28)
print(a[0, 0, 2, 4]) #具体到某个元素
print(a[:2, :1, :, :].shape) #在第一个维度上取 0 和 1, 在第二个维度上取 0
print(a[:2, 1:, :, :].shape) #在第一个维度上取 0 和 1, 在第二个维度上取 1,2
print(a[:2,2:, :, :].shape) # 在第一个维度上取 0 和 1, 在第二个维度上取 1,2
print(a[:, :, 0:28:2, 0:28:2].shape) # step=2隔行采样
print(a[:, :, ::2, ::2].shape) #等同于这个
print(a[:, 1, ...].shape)
print(a[..., :2].shape)
print(a[0, ..., ::2].shape)

tensor(0.0323)
torch.Size([2, 1, 28, 28])
torch.Size([2, 2, 28, 28])
torch.Size([2, 1, 28, 28])
torch.Size([4, 3, 14, 14])
torch.Size([4, 3, 14, 14])
torch.Size([4, 28, 28])
torch.Size([4, 3, 28, 2])
torch.Size([3, 28, 14])
